PR: Indentation
drazen04/alfresco-rest-api-client pull request #7
Opened 2022-10-18 18:56 UTC by Daniele-DelVecchio

Only indentation.

2022-10-18 21:01 UTC, drazen04 approved these changes

2022-10-18 21:15 UTC, drazen04 requested changes
Thanks, good change.
- I think that you could do better avoiding pass AlfrescoRestApi as parameter;
- It would nice to refactor method's names like "Delete", "Post" etc.

Also, i think i could be useful to create an "abstract" representation of Response beyond JSONObject (maybe will be another pr).

2022-10-19 19:19 UTC, Daniele-DelVecchio commented
Fix interface http methods.

2022-10-23 20:18 UTC, drazen04 approved these changes

2022-10-23 20:18 UTC, merged